version: '3.7'

services:
  php-fpm:
    user: www-data
    image: registry.skyeng.tv/base/php8.0-buster:1.13.21
    deploy:
      resources:
        limits:
          memory: 8G
    env_file:
      - utils/symfony-application/.env
    environment:
      - SYMFONY_DEPRECATIONS_HELPER=weak
      - APP_DEBUG=0
    volumes:
      - .:/opt/app:cached
    depends_on:
      - skyeng-postgresql11

  skyeng-postgresql11:
    image: registry.skyeng.tv/dev/postgres11:0.0.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - 5438:5432
