---
version: '2'

tasks:
    setup:
        desc: "Setup dev env"
        cmds:
            - task: up
            - docker-compose exec -e COMPOSER_MEMORY_LIMIT=-1 php-fpm composer install
            - docker-compose exec php-fpm utils/symfony-application/bin/console d:m:m -n --env=test
            - docker-compose exec php-fpm utils/symfony-application/bin/console a:i utils/symfony-application/public -n  --env=test

    up:
        desc: "Up all containers"
        cmds:
            - docker-compose build --pull
            - docker-compose up -d --remove-orphans

    down:
        desc: "Down all containers"
        cmds:
            - docker-compose down

    sh:
        desc: "Jump into application container"
        cmds:
            - docker-compose exec php-fpm bash

    start-web-server:
        desc: "Start symfony local web server"
        cmds:
            - docker-compose exec php-fpm symfony server:stop
            - docker-compose exec php-fpm symfony server:start -d

    stop-web-server:
        desc: "Stop symfony local web server"
        cmds:
            - docker-compose exec php-fpm symfony server:stop

    test:
        desc: "Test headless cms"
        cmds:
            - docker-compose exec php-fpm composer codecept

    phpstan:
        desc: "Phpstan analyse"
        cmds:
            - docker-compose exec php-fpm composer phpstan

    rector:
        desc: "Phpstan analyse"
        cmds:
            - docker-compose exec php-fpm composer rector

    php-cs-fixer:
        desc: "Phpstan analyse"
        cmds:
            - docker-compose exec php-fpm composer php-cs-fixer

    deptrac:
        desc: "Phpstan analyse"
        cmds:
            - docker-compose exec php-fpm composer deptrac

    psalm:
        desc: "Phpstan analyse"
        cmds:
            - docker-compose exec php-fpm composer psalm
