Skyeng\MarketingCmsBundle\Domain\Entity\Resource:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: uri
  properties:
    uri:
      - Regex: '~^/.{1,}$~'

Skyeng\MarketingCmsBundle\Domain\Entity\File:
  properties:
    resource:
      - Valid: ~

Skyeng\MarketingCmsBundle\Domain\Entity\Redirect:
  properties:
    resource:
      - Valid: ~

# Model Component

Skyeng\MarketingCmsBundle\Application\Cms\Component\Dto\Save\ComponentDto:
  properties:
    id:
      - Uuid: ~
    templateId:
      - Uuid: ~

Skyeng\MarketingCmsBundle\Application\Cms\Component\Dto\Save\SaveModelComponentsV1RequestDto:
  properties:
    modelId:
      - NotBlank: ~
      - Uuid: ~

# Template Component

Skyeng\MarketingCmsBundle\Application\Cms\TemplateComponent\Dto\Save\SaveTemplateComponentsV1RequestDto:
  properties:
    templateId:
      - NotBlank: ~
      - Uuid: ~

Skyeng\MarketingCmsBundle\Application\Cms\TemplateComponent\Dto\Save\ComponentDto:
  properties:
    id:
      - Uuid: ~

# Media

Skyeng\MarketingCmsBundle\Domain\Entity\MediaCatalog:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

Skyeng\MarketingCmsBundle\Application\Cms\MediaFile\Dto\AddMediaFile\AddMediaFileV1RequestDto:
  properties:
    file:
      - NotBlank: ~

Skyeng\MarketingCmsBundle\Domain\Entity\MediaFile:
  properties:
    catalog:
      - NotBlank: ~
