Skyeng\MarketingCmsBundle\Domain\Entity\Resource:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: uri
  properties:
    uri:
      - Regex: '~^/.{1,}$~'

Skyeng\MarketingCmsBundle\Domain\Entity\File:
  properties:
    resource:
      - Valid: ~

Skyeng\MarketingCmsBundle\Domain\Entity\Redirect:
  properties:
    resource:
      - Valid: ~

# Page

Skyeng\MarketingCmsBundle\Domain\Entity\PageComponent:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [page, order]
        errorPath: order
        message: 'Это значение уже используется для этой страницы'
  properties:
    order:
      - NotBlank: ~
      - Positive: ~

Skyeng\MarketingCmsBundle\Domain\Entity\PageCustomMetaTag:
  properties:
    content:
      - NotBlank: ~

Skyeng\MarketingCmsBundle\Domain\Entity\Page:
  properties:
    resource:
      - Valid: ~
    components:
      - Valid: ~
    customMetaTags:
      - Valid: ~

# Media

Skyeng\MarketingCmsBundle\Domain\Entity\MediaCatalog:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

Skyeng\MarketingCmsBundle\Domain\Entity\MediaFile:
  properties:
    file:
      - File: { maxSize: 20M, mimeTypes: [ image/jpeg, image/png, image/gif, application/pdf, video/mp4 ] }
    catalog:
      - NotBlank: ~
