doctrine:
  dbal:
    types:
      cms_id: 'Skyeng\MarketingCmsBundle\Infrastructure\Doctrine\Type\IdType'
      cms_uri: 'Skyeng\MarketingCmsBundle\Infrastructure\Doctrine\Type\UriType'
      cms_resource_type: 'Skyeng\MarketingCmsBundle\Infrastructure\Doctrine\Type\ResourceType'
      cms_content_type: 'Skyeng\MarketingCmsBundle\Infrastructure\Doctrine\Type\ContentType'
      cms_cache_time: 'Skyeng\MarketingCmsBundle\Infrastructure\Doctrine\Type\CacheTimeType'

  orm:
    entity_managers:
      default:
        mappings:
          MarketingCmsBundle:
            type: xml
            prefix: 'Skyeng\MarketingCmsBundle\Domain\Entity'
            dir: 'Infrastructure/Doctrine/Entity/mapping'
            alias: MarketingCmsBundle
