nelmio_api_doc:
  documentation:
    definitions:
      MarketingCmsJsonResponseOk:
        type: object
        required:
          - message
          - data
        properties:
          message:
            type: string
            description: Инф. сообщение
          data:
            type: object
      MarketingCmsJsonResponseError:
        type: object
        required:
          - message
          - errors
        properties:
          message:
            type: string
            description: Инф. сообщение
          errors:
            type: array
            description: Список ошибок
            items:
              type: object
              required:
                - key
                - message
                - code
              properties:
                key:
                  type: string
                  description: Ключ ошибки
                message:
                  type: string
                  description: Сообщение об ошибке
                code:
                  type: string
                  description: Код ошибки
      MarketingCmsJsonResponseException:
        type: object
        required:
          - message
          - exceptionMessage
        properties:
          message:
            type: string
            description: Текст ошибки
          exceptionMessage:
            type: string
            description: Текст исключения
          exceptionType:
            type: string
            description: Тип исключения
          stackTrace:
            type: object
            description: Stack trace
