vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        media_files:
            uri_prefix: '%app.uploads_base_url%'
            upload_destination: 'uploads.nfs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
