parameters:
    env(UPLOADS_BASE_URL): '/uploads'

vich_uploader:
    mappings:
        cms_media_files:
            uri_prefix: '%env(UPLOADS_BASE_URL)%'
            upload_destination: 'uploads.nfs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
