services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $editorDefinition: '%marketing_cms.editor_definition%'

  Skyeng\MarketingCmsBundle\:
    resource: '../../*'
    exclude:
      - '../../tests'
      - '../../**/{Dto,ValueObject,Entity,Exception}/*.php'
      - '../../Domain/{Exception,Traits,Entity,Event}'
      - '../../Domain/{Exception,Traits,Entity,Event}/*.php'
      - '../../Domain/{Exception,Traits,Entity,Event}/**/*.php'

  Skyeng\MarketingCmsBundle\Application\Cms\Model\Assembler\LocalizedModelAsArrayAssembler:
    arguments:
      $fieldValueGetter: '@Skyeng\MarketingCmsBundle\Application\Cms\Model\Assembler\DatetimeFieldValueGetter'

  Skyeng\MarketingCmsBundle\Application\Cms\Model\Assembler\DatetimeFieldValueGetter:
    arguments:
      $next: '@Skyeng\MarketingCmsBundle\Application\Cms\Model\Assembler\ComponentFieldValueGetter'

  Skyeng\MarketingCmsBundle\Application\Cms\Model\Assembler\ComponentFieldValueGetter:
    arguments:
      $next: '@Skyeng\MarketingCmsBundle\Application\Cms\Model\Assembler\DefaultFieldValueGetter'
