services:
  _defaults:
    autowire: true
    autoconfigure: true

  Skyeng\MarketingCmsBundle\:
    resource: '../../*'
    exclude:
      - '../../tests'
      - '../../**/{Dto,ValueObject,Model,Entity,Exception}/*.php'
      - '../../Domain/{Exception,Traits,Entity,Event}'
      - '../../Domain/{Exception,Traits,Entity,Event}/*.php'
      - '../../Domain/{Exception,Traits,Entity,Event}/**/*.php'

  marketing_cms_bundle.listener.media_file_updated_listener:
    class: Skyeng\MarketingCmsBundle\EventListener\MediaFileUpdatedListener
    tags:
      - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
      - { name: doctrine.event_listener, event: prePersist, method: prePersist }
