marketing_cms:
    editor:
        show_editor_link: true
        security:
            enabled: false
    locales: [en, ru]
    default_locale: en
    models:
        article:
            name: article
            label: Статья
            cloneable: true
            fields:
                - name: title
                  type: Text
                  label: Название
                  hooks:
                      - setPrefixOnClone
                - name: url
                  type: Text
                  label: Ссылка
                  hooks:
                      - setPrefixOnClone
                - name: description
                  type: Text
                  label: Описание
                  required: false
                  cloneable: false
                - name: content
                  type: Textarea
                  label: Контент
                - name: published
                  type: Boolean
                  label: Опубликовано
                  group: Дополнительно

                - name: created_at
                  type: DateTime
                  label: Дата создания
                  group: Основные данные
                  hide_on_index: false
                  hide_on_form: false
                  hooks:
                      - setCurrentDateTimeOnCreate

                - name: updated_at
                  type: DateTime
                  label: Дата последнего изменения
                  group: Основные данные
                  hide_on_index: false
                  hide_on_form: false
                  hooks:
                      - setCurrentDateTimeOnCreate
                      - setCurrentDateTimeOnUpdate

        webinar:
            name: webinar
            label: Вебинар
            fields:
                - name: title
                  label: Название
                  type: Text
                - name: url
                  label: Ссылка
                  type: Text
                - name: complexity
                  label: Сложность
                  type: Choice
                  options:
                      choices:
                          - label: высокая
                            value: high
                          - label: средняя
                            value: medium
                          - label: низкая
                            value: low
                - name: cost
                  label: Цена
                  type: Integer
        tag:
            name: tag
            label: Тег
            fields:
                - name: slug
                  label: Слаг
                  type: Text
                - name: title
                  localized: true
                  label: Название
                  type: Text
                - name: components
                  localized: true
                  group: Компоненты
                  label: Компоненты
                  type: Components
                  hooks:
                      - setNullOnCreate
