Skyeng\MarketingCmsBundle\Application\Cms\MediaFile\Dto\AddMediaFile\AddMediaFileV1RequestDto:
  properties:
    file:
      - File:
          # Дублирует валидацию у Skyeng\MarketingCmsBundle\Domain\Entity\MediaFile
          maxSize: 20M
          mimeTypes:
            # image
            - image/jpeg
            - image/png
            - image/gif
            - image/svg+xml
            - image/svg
            - image/webp
            # pdf
            - application/pdf
            # video
            - video/mp4
            - video/mpeg
            - video/x-flv
            - video/x-msvideo
            # archive
            - application/x-rar-compressed
            - application/zip
            # text
            - text/csv
            - text/xml
            - text/plain
            - text/markdown
            # audio
            - audio/mp4
            - audio/aac
            - audio/mpeg
            # vnd
            - application/vnd.oasis.opendocument.text
            - application/vnd.oasis.opendocument.spreadsheet
            - application/vnd.oasis.opendocument.presentation
            - application/vnd.oasis.opendocument.graphics
            - application/vnd.ms-excel
            - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
            - application/vnd.ms-excel.sheet.macroEnabled.12
            - application/vnd.ms-powerpoint
            - application/vnd.openxmlformats-officedocument.presentationml.presentation
            - application/msword
            - application/vnd.openxmlformats-officedocument.wordprocessingml.document
            - application/vnd.mozilla.xul+xml
            - application/vnd.google-earth.kml+xml

Skyeng\MarketingCmsBundle\Domain\Entity\MediaFile:
  properties:
    file:
      - File:
          # Дублирует валидацию у Skyeng\MarketingCmsBundle\Application\Cms\MediaFile\Dto\AddMediaFile\AddMediaFileV1RequestDto
          maxSize: 20M
          mimeTypes:
            # image
            - image/jpeg
            - image/png
            - image/gif
            - image/svg+xml
            - image/svg
            - image/webp
            # pdf
            - application/pdf
            # video
            - video/mp4
            - video/mpeg
            - video/x-flv
            - video/x-msvideo
            # archive
            - application/x-rar-compressed
            - application/zip
            # text
            - text/csv
            - text/xml
            - text/plain
            - text/markdown
            # audio
            - audio/mp4
            - audio/aac
            - audio/mpeg
            # vnd
            - application/vnd.oasis.opendocument.text
            - application/vnd.oasis.opendocument.spreadsheet
            - application/vnd.oasis.opendocument.presentation
            - application/vnd.oasis.opendocument.graphics
            - application/vnd.ms-excel
            - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
            - application/vnd.ms-excel.sheet.macroEnabled.12
            - application/vnd.ms-powerpoint
            - application/vnd.openxmlformats-officedocument.presentationml.presentation
            - application/msword
            - application/vnd.openxmlformats-officedocument.wordprocessingml.document
            - application/vnd.mozilla.xul+xml
            - application/vnd.google-earth.kml+xml
